source 'https://github.com/CocoaPods/Specs.git'

target 'MutableDeepCopy', :exclusive => true do
  pod "MutableDeepCopy", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MutableDeepCopy", :path => "../"

  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
